spring.application.name=demo
springdoc.api-docs.path=/api-docs
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=shutdown
management.endpoints.web.base-path=/admin/actuator
spring.security.user.name=admin
spring.security.user.password=secret
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.path=/swagger-ui.html

