spring.application.name=demo
springdoc.api-docs.path=/v3/api-docs

spring.main.allow-bean-definition-overriding=true
spring.test.context.failure-threshold=5

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.kafka.bootstrap-servers=localhost:29093
spring.kafka.consumer.group-id=your-topic-name-group
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual_immediate

spring.kafka.consumer.bootstrap-servers=localhost:29093
topic-name=article-topic
group.id=group-1

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.enable-idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=20
spring.kafka.producer.max-in-flight-requests-per-connection=5

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=hw6
spring.cassandra.local-datacenter=datacenter1

spring.flyway.url=jdbc:postgresql://localhost:5432/mydatabase
spring.flyway.user=myuser
spring.flyway.password=mypassword
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=create
spring.flyway.baselineOnMigrate=true

logging.level.com.example.demo.controller=DEBUG
logging.level.com.example.demo.model=DEBUG
