spring.application.name=demo
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.example.demo.controller=DEBUG
logging.level.com.example.demo.model=DEBUG
