version: '3.8'  # Укажите версию Docker Compose

services:
  postgres:
    image: postgres:latest  # Используйте последнюю версию PostgreSQL
    container_name: my_postgres  # Имя контейнера
    environment:
      POSTGRES_DB: mydatabase  # Имя базы данных
      POSTGRES_USER: myuser     # Имя пользователя
      POSTGRES_PASSWORD: mypassword  # Пароль пользователя
    ports:
      - "5432:5432"  # Проброс порта
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных

volumes:
  postgres_data:  # Определение тома для хранения данных