version: '3.8'  # Укажите версию Docker Compose

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - '29093:29093'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 100000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  postgres:
    image: postgres:latest  # Используйте последнюю версию PostgreSQL
    container_name: my_postgres  # Имя контейнера
    environment:
      POSTGRES_DB: mydatabase  # Имя базы данных
      POSTGRES_USER: myuser     # Имя пользователя
      POSTGRES_PASSWORD: mypassword  # Пароль пользователя
    ports:
      - "5432:5432"  # Проброс порта
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: my_cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_SEEDS: cassandra
    ports:
      - "9042:9042"  # CQL
    volumes:
      - cassandra_data:/var/lib/cassandra  # Persistent storage

volumes:
  postgres_data:  # Определение тома для хранения данных
  cassandra_data: