name: Java CI

on:
  push:
    branches:
      - main
      - 'sem2/*'
  pull_request:
    branches:
      - main
      - 'sem2/*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432

      cassandra:
        image: cassandra:latest
        env:
          CASSANDRA_CLUSTER_NAME: my_cluster
          CASSANDRA_DC: dc1
          CASSANDRA_RACK: rack1
        ports:
          - 9042:9042  # CQL

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        env:
          SPRING_DATABASE_URL: jdbc:postgresql://localhost:5432/mydatabase
          SPRING_DATABASE_USERNAME: myuser
          SPRING_DATABASE_PASSWORD: mypassword
        run: mvn test